input_data:
  file1: "../data/raw/Beginner_Climate_Change_Dataset_20_Features_1200_Rows.csv"
  file2: "../data/raw/realistic_ocean_climate_dataset.csv"
  file3: "../data/raw/ocean_health_index.csv"
  file4: "../data/raw/global_bleaching_environmental.csv"
  file5: "../data/raw/Nasa global warming.csv"
  File6: "../data/raw/tas_Berkeley_Earth.csv"
  file7: "../data/raw/tas_ERA5.csv"
  file8: "../data/raw/tas_GISTEMP.csv"
  file9: "../data/raw/tas_NOAAGlobalTemp.csv"
  file10: "../data/raw/tas_JRA-55.csv"
  
 output_data:
  file1: "../data/clean/climate_change_cleaned.csv"
  file2: "../data/clean/global_bleaching_cleaned.csv"
  file3: "..data/clean/ocean_climate_clean.csv"
